CREATE TABLE wildfire_info (
	id SERIAL PRIMARY KEY,
	fire_name TEXT,
    fire_size INT,
    fire_size_class TEXT,
    stat_cause_descr TEXT,
    latitude VARCHAR (255),         
    longitude VARCHAR (255),           
    state VARCHAR (255),              
    disc_clean_date DATE,   
    cont_clean_date DATE,    
    discovery_month VARCHAR (255),   
    disc_date_final VARCHAR (255),    
    cont_date_final VARCHAR (255),     
    putout_time VARCHAR (255),      
    disc_date_pre DATE,      
    disc_pre_year INT,     
    disc_pre_month VARCHAR (255),      
    wstation_usaf VARCHAR (255),       
    dstation_m INT,      
    wstation_wban INT,     
    wstation_byear INT,     
    wstation_eyear INT,      
    vegetation INT,          
    fire_mag FLOAT,       
    weather_file VARCHAR (255),        
    temp_pre_30 FLOAT,        
    temp_pre_15 FLOAT,         
    temp_pre_7 FLOAT,          
    temp_cont FLOAT,        
    wind_pre_30 FLOAT,        
    wind_pre_15 FLOAT,         
    wind_pre_7 FLOAT,          
    wind_cont FLOAT,         
    hum_pre_30 FLOAT,         
    hum_pre_15 FLOAT,          
    hum_pre_7 FLOAT,           
    hum_cont FLOAT,      
    prec_pre_30 FLOAT,        
    prec_pre_15 FLOAT,         
    prec_pre_7 FLOAT,          
    prec_cont FLOAT,           
    remoteness FLOAT
);

SELECT * FROM wildfire_info;