CREATE TABLE wildfire_info (
	id SERIAL PRIMARY KEY,
	fire_name TEXT,
    fire_size INT,
    fire_size_class TEXT,
    stat_cause_descr TEXT,
    latitude VARCHAR (255),         
    longitude VARCHAR (255),           
    state VARCHAR (255),              
    disc_clean_date DATE,   
    cont_clean_date DATE,    
    discovery_month VARCHAR (255),   
    disc_date_final DATE,    
    cont_date_final DATE,     
    putout_time VARCHAR (255),      
    disc_date_pre VARCHAR (255),      
    disc_pre_year VARCHAR (255),     
    disc_pre_month VARCHAR (255),      
    wstation_usaf VARCHAR (255),       
    dstation_m VARCHAR (255),      
    wstation_wban VARCHAR (255),     
    wstation_byear VARCHAR (255),     
    wstation_eyear VARCHAR (255),      
    vegetation VARCHAR (255),          
    fire_mag VARCHAR (255),       
    weather_file VARCHAR (255),        
    temp_pre_30 VARCHAR (255),        
    temp_pre_15 VARCHAR (255),         
    temp_pre_7 VARCHAR (255),          
    temp_cont VARCHAR (255),        
    wind_pre_30 VARCHAR (255),        
    wind_pre_15 VARCHAR (255),         
    wind_pre_7 VARCHAR (255),          
    wind_cont VARCHAR (255),         
    hum_pre_30 VARCHAR (255),         
    hum_pre_15 VARCHAR (255),          
    hum_pre_7 VARCHAR (255),           
    hum_cont VARCHAR (255),      
    prec_pre_30 VARCHAR (255),        
    prec_pre_15 VARCHAR (255),         
    prec_pre_7 VARCHAR (255),          
    prec_cont VARCHAR (255),           
    remoteness VARCHAR (255)
);

SELECT * FROM wildfire_info;